FROM node:20-alpine

WORKDIR /app

RUN npm install -g @angular/cli

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4200

# Use --poll to enable hot-reloading in Docker
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "1000"]